# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'renshenglogin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
   
  # Pods for renshenglogin

	pod 'Firebase/Core'
	pod 'Firebase/Database'
    pod 'Firebase/Storage'
	
	#add firebaseUI to the app
	pod 'FirebaseUI/Auth'
	pod 'FirebaseUI/Google' 
	pod 'FirebaseUI/Facebook'
	pod 'FirebaseUI/Phone'
    pod 'MessageKit'

	#enable facebook login
    pod 'FBSDKLoginKit'

end
