platform :ios, '11.2'

target 'renshenglogin' do
project'/Users/cynthiaghf/Desktop/Blush/Code/renshenglogin/renshenglogin.xcodeproj
use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'MessageKit'

end
